version: '3'
services:
  container_bdd_dev:
    image: "mongo:5.0.8"
    container_name: 'container_bdd_dev'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${BDD_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${BDD_PASSWORD}
    volumes:
      - volume_database_dev:/data/db
    ports:
      - '${BDD_PORT}:27017'

  container_backend_dev:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    image: backend_template:backend_dev
    container_name: container_backend_dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      BDD_HOST: container_bdd_dev
      BDD_PORT: ${BDD_PORT}
      BDD_USERNAME: ${BDD_USERNAME}
      BDD_PASSWORD: ${BDD_PASSWORD}
      TOKEN_PASSWORD: ${TOKEN_PASSWORD}
      TOKEN_EMAIL_PASSWORD: ${TOKEN_EMAIL_PASSWORD}
      GMAIL_ACCOUNT_EMAIL: ${GMAIL_ACCOUNT_EMAIL}
      GMAIL_ACCOUNT_PASSWORD: ${GMAIL_ACCOUNT_PASSWORD}
      FRONTEND_VERIF_EMAIL_URL: ${FRONTEND_VERIF_EMAIL_URL}
      FRONTEND_lOST_PASSWORD_URL: ${FRONTEND_lOST_PASSWORD_URL}
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - container_bdd_dev

volumes:
  volume_database_dev: