version: '3'
services:
  container_bdd_dev:
    image: "mongo:5.0.8"
    container_name: 'container_bdd_dev'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${BDD_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${BDD_PASSWORD}
    volumes:
      - volume_database_dev:/data/db
    ports:
      - '${BDD_PORT}:27017'

  container_backend_dev:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    image: backend_template:backend_dev
    container_name: container_backend_dev
    volumes:
      - ./backend/routes:/usr/src/app/routes
      - ./backend/functions:/usr/src/app/functions
      - ./backend/schemas:/usr/src/app/schemas
      - ./backend/app.js:/usr/src/app/app.js
    environment:
      BDD_HOST: container_bdd_dev
      BDD_PORT: ${BDD_PORT}
      BDD_USERNAME: ${BDD_USERNAME}
      BDD_PASSWORD: ${BDD_PASSWORD}
      TOKEN_PASSWORD: ${TOKEN_PASSWORD}
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - container_bdd_dev

volumes:
  volume_database_dev: